version: "3.76"
services:
  db:
    image: "postgres"
    volumes:
      - ./Misc/Scripts/tables.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: Acme
      POSTGRES_DB: AcmeExchanger
  api:
    build:
      dockerfile: ../Misc/Dockerfile
      context: src/.
      args:
        PROJECT_NAME: AcmeExchangeR.API
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5010:5010"
    depends_on:
      - db